@startuml
skinparam svgDimensionStyle false
hide footbox

participant "[[system-actors.html#Holder Holder]]\n(as VHL Holder)" as Holder
participant "[[system-actors.html#Issuer Issuer]]\n(as PCF Consent Recorder,\n as VHL Sharer)" as Issuer
participant "[[system-actors.html#ConsentRegistry Consent Registry]]" as PCFConsentRegistry
participant "Document Generator" as DocumentGenerator
participant "Document Signer" as DocumentSigner
participant "[[system-actors.html#Receiver Receiver]]\n(as VHL Receiver)" as Receiver



activate Holder
activate Issuer


Holder -> Issuer : (Optional) [[#consent-selection Select consent directives]]			
		
Holder -> Issuer : Generate VHL request [ITI-YY3] \n(as VHL Holder and VHL Sharer)				
alt use reference architecture
  Issuer -> DocumentGenerator: Generate document request\n [DocumentReference/$docref]
  DocumentGenerator -> Issuer: Generate document response\n [DocumentReference/$docref]
else use bespoke means
  Issuer -> Issuer : generate document
end

group optional signing
  alt use reference architecture			
    Issuer -> DocumentSigner: Sign document request
    DocumentSigner -> DocumentSigner: generate digital signatures\n for verification 
    DocumentSigner -> Issuer: return document manifest containing\n generated doc, signed collateral
  else use bespoke means
    Issuer -> Issuer: generate doc and signed collateral
  end					
end 
					
Issuer -> Issuer : generate VHL authorization mechanism		
		
Issuer -> Holder : Generate VHL response [ITI-YY3] \n(as  VHL Sharer and VHL Holder)
deactivate Issuer
... time passes ...				

Holder -> Receiver : Provide VHL  [ITI-YY6]\n (as VHL Holder and VHL Receiver)
Receiver -> Issuer : Request VHL Documents request [ITI-YY4]\n (as VHL Receiver and VHL Sharer)
Receiver -> Issuer : Request VHL Documents response [ITI-YY4]\n (as VHL Receiver and VHL Sharer)
loop
 Receiver -> Issuer : Request VHL Document request [ITI-YY5]\n (as VHL Receiver and VHL Sharer)
 Issuer -> Receiver : Request VHL Document response [ITI-YY5]\n (as VHL Sharer and VHL Receiver)
end loop

@enduml
